import { EmployeeResponse } from '../../core/_models';

export const mockEmployees: EmployeeResponse[] = [
    {
        _id: '1',
        apellidoMaterno: 'Pérez',
        apellidoPaterno: 'González',
        area: 'Recursos Humanos',
        cargo: 'Analista',
        correoPersonal: 'juan.perez@gmail.com',
        correoTrabajo: 'juan.perez@empresa.com',
        createdAt: '2023-01-01T00:00:00Z',
        direccion: 'Av. Principal 123',
        distrito: 'Lima',
        dni: '12345678',
        estadoCivil: 'Soltero',
        fechaIngresoArea: '2021-01-01T00:00:00Z',
        fechaIngresoEmpresa: '2020-01-01T00:00:00Z',
        fechaFinContrato: '2023-12-31T00:00:00Z',
        fechaNacimiento: '1990-01-01T00:00:00Z',
        firmaDigital: 'Sí',
        genero: 'Masculino',
        nacionalidad: 'Peruano',
        nombres: 'Juan',
        reconocimientoFacial: 'Sí',
        rollSistemaDigitalizado: 'Empleado',
        sedeTrabajo: 'Sede Central',
        status: 'Activo',
        telefonoPersonal: '987654321',
        updatedAt: '2023-01-01T00:00:00Z',
        indicativoTel: '+51',
        indicativoTelLaboral: '+51',
        telefonoLaboral: '123456789',
        codigoTrabajador: 'EMP001',
        tipoContrato: 'Indefinido',
    },
];