export interface Employee {
    area: string,
    cargo: string,
    firmaDigital: string,
    recFacial: null,
    nacionalidad: string,
    estadoCivil: string,
    genero: string,
    dni: string,
    fechaNacimiento: string,
    nombres: string,
    apellidoPaterno: string,
    apellidoMaterno: string,
    distrito: string,
    direccion: string,
    corpEmail: string,
    perEmail: string,
    indicativoTel: number,
    telefono: number,
    fechaIngresoArea: string,
    FechaIngresoEmp: string,
    tipoRol: string,
    status: string,
    sedeTrabajo: string
}