export interface Worker {
	_id?: string;
	name?: string | null;
	lastname?: string | null;
	email: string;
	password?: string | null;
	dni: string;
	mothers_lastname: string;
	fathers_lastname: string;
	birthDate: string;
	companyAreaId: string;
	charge: string;
	entryDate: string;
	contractTerminationDate?: string | null;
	areaEntryDate: string;
	province: string;
	city: string;
	address: string;
	district: string;
	corporateEmail: string;
	nationalityId: string;
	gender: 'Masculino' | 'Femenino';
	civilStatus: 'Soltero/a' | 'Casado/a' | 'Divorciado/a' | 'Conviviente' | 'Viudo/a';
	personalPhone: string;
	facialRecognition?: string | null;
	digitalSignature?: string | null;
	status: 'Activo' | 'Inactivo';
	workSiteId: string;
	rolId: string;
	sizePants: 26 | 28 | 30 | 32 | 34 | 36 | 38 | 40 | 42 | 44;
	sizePolo: 'XS' | 'S' | 'M' | 'L' | 'XL' | 'XXL' | 'XXXL';
	sizeShoe: 36 | 38 | 40 | 42 | 44;
	companyIds: string[];
	createdAt?: string;
	updatedAt?: string;
}

export interface WorkerResponse {
	_id: string;
	name?: string | null;
	lastname?: string | null;
	email: string;
	dni: string;
	mothers_lastname: string;
	fathers_lastname: string;
	birthDate: string;
	companyAreaId: string;
	charge: string;
	entryDate: string;
	contractTerminationDate?: string | null;
	areaEntryDate: string;
	province: string;
	city: string;
	address: string;
	district: string;
	corporateEmail: string;
	nationalityId: string;
	gender: 'Masculino' | 'Femenino';
	civilStatus: 'Soltero/a' | 'Casado/a' | 'Divorciado/a' | 'Conviviente' | 'Viudo/a';
	personalPhone: string;
	facialRecognition?: string | null;
	digitalSignature?: string | null;
	status: 'Activo' | 'Inactivo';
	workSiteId: string;
	rolId: string;
	sizePants: 26 | 28 | 30 | 32 | 34 | 36 | 38 | 40 | 42 | 44;
	sizePolo: 'XS' | 'S' | 'M' | 'L' | 'XL' | 'XXL' | 'XXXL';
	sizeShoe: 36 | 38 | 40 | 42 | 44;
	companyIds: string[];
}

export interface WorkerRequest {
	name?: string | null;
	lastname?: string | null;
	email: string;
	password?: string | null;
	dni: string;
	mothers_lastname: string;
	fathers_lastname: string;
	birthDate: string;
	companyAreaId: string;
	charge: string;
	entryDate: string;
	contractTerminationDate?: string | null;
	areaEntryDate: string;
	province: string;
	city: string;
	address: string;
	district: string;
	corporateEmail: string;
	nationalityId: string;
	gender: 'Masculino' | 'Femenino';
	civilStatus: 'Soltero/a' | 'Casado/a' | 'Divorciado/a' | 'Conviviente' | 'Viudo/a';
	personalPhone: string;
	facialRecognition?: string | null;
	digitalSignature?: string | null;
	status: 'Activo' | 'Inactivo';
	workSiteId: string;
	rolId: string;
	sizePants: 26 | 28 | 30 | 32 | 34 | 36 | 38 | 40 | 42 | 44;
	sizePolo: 'XS' | 'S' | 'M' | 'L' | 'XL' | 'XXL' | 'XXXL';
	sizeShoe: 36 | 38 | 40 | 42 | 44;
}